export interface Lead {
  id: string;
  name: string;
  type: "physio" | "chiro" | "osteo" | "multi" | "wellness";
  town: string;
  phone: string;
  phoneLandline?: string;
  website?: string;
  notes: string;
  tier: 1 | 2 | 3;
  signal: "hiring" | "ads" | "local" | "hiring+local" | "ads+local";
  batch: string;
  batchLabel: string;
}

// Lead data — compiled from farnham-physio-leads.md, physio-leads.md, uk-physio-chiro-osteo-ad-leads.md
// Generated: 10 Feb 2026
// Total leads after dedup: 101
export const LEADS: Lead[] = [
  // ============================================================
  // FARNHAM LOCAL LEADS (signal: "local")
  // ============================================================

  // --- Test lead (safe to call) ---
  {
    id: "test-lead-2",
    name: "TEST — CallingMode Test",
    type: "physio" as const,
    town: "Farnham",
    phone: "07700900000",
    notes: "BT test number — safe to dial, won't connect to anyone",
    tier: 1 as const,
    signal: "hiring" as const,
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },

  // --- Priority leads (mobile numbers) ---
  {
    id: "back-to-action-physiotherapy",
    name: "Back to Action Physiotherapy",
    type: "physio",
    town: "Farnham",
    phone: "07376067379",
    website: "backtoaction.co.uk",
    notes: "Solo practitioner, also does mobile physio covering Haslemere/Liphook/Liss. Based at IN2 Training gym",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "foster-chiropractic",
    name: "Foster Chiropractic",
    type: "chiro",
    town: "Farnham",
    phone: "07796018796",
    website: "fosterchiropractic.co.uk",
    notes: "Small independent clinic, 12 Old Compton Lane",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "coombe-house-clinic",
    name: "Coombe House Clinic",
    type: "osteo",
    town: "Farnham",
    phone: "07951133697",
    website: "coombehouseclinic.co.uk",
    notes: "Solo practitioner (Fleur Robertson), founded 2017. Cambridge House, East Street",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "charlotte-hunt-osteopaths",
    name: "Charlotte Hunt Osteopaths",
    type: "osteo",
    town: "Farnham (Lower Bourne)",
    phone: "07957563472",
    website: "charlottehuntosteopaths.co.uk",
    notes: "Solo practitioner, also has Coulsdon clinic. School hours Mon/Wed/Thu",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "farnham-natural-therapy-clinic",
    name: "Farnham Natural Therapy Clinic",
    type: "multi",
    town: "Farnham",
    phone: "07866141353",
    website: "farnhamnaturaltherapy.co.uk",
    notes: "Multi-therapist clinic, Hones Business Park",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "physio-in-motion",
    name: "Physio in Motion",
    type: "physio",
    town: "Farnham",
    phone: "07889890718",
    phoneLandline: "01252716611",
    website: "physioinmotion.co.uk",
    notes: "Solo practitioner (James Leyland), Waverley Clinic, East Street",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "midas-physiotherapy",
    name: "Midas Physiotherapy",
    type: "physio",
    town: "Farnham",
    phone: "07738074289",
    phoneLandline: "01252501373",
    website: "midasphysiotherapy.co.uk",
    notes: "Small clinic est. 2009, Farnham Business Park. Has both landline and mobile",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "back-on-track-chiropractic",
    name: "Back On Track Chiropractic",
    type: "chiro",
    town: "Farnham",
    phone: "07825777217",
    phoneLandline: "01252781133",
    website: "back-on-track.biz",
    notes: "Solo practitioner (Sukie Brockman), Alexander House, Waverley Lane",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "farnham-physiotherapy-sports-clinic",
    name: "Farnham Physiotherapy & Sports Clinic",
    type: "physio",
    town: "Farnham",
    phone: "07899544569",
    phoneLandline: "01252726479",
    website: "farnham-physiotherapy.co.uk",
    notes: "Established clinic, 20 Firgrove Hill. WhatsApp number available. 15+ yrs experience, open 6 days",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "dr-sean-chiropractor",
    name: "Dr Sean Chiropractor",
    type: "chiro",
    town: "Fleet",
    phone: "07942305554",
    website: "schiropractor.com",
    notes: "Solo practitioner, 27+ years experience. Stockton Avenue, Fleet",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "front-foot-physiotherapy",
    name: "Front Foot Physiotherapy",
    type: "physio",
    town: "Frimley Green",
    phone: "07413674694",
    website: "frontfootphysiotherapy.co.uk",
    notes: "Solo practitioner (Katherine), serves Camberley/Farnborough/Fleet. The Hatches",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "health-at-hart",
    name: "Health at Hart",
    type: "osteo",
    town: "Hartley Wintney",
    phone: "07921076758",
    website: "healthathart.co.uk",
    notes: "20+ years experience, cranial osteopathy. Old Post Office, High Street. Serves Fleet/Hook area",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "foundations-physio",
    name: "Foundations Physio",
    type: "physio",
    town: "Bordon / Farnham",
    phone: "07817495791",
    website: "foundationsphysio.co.uk",
    notes: "Covers Bordon, Aldershot, Farnham. Also has hydrotherapy",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "mansfield-park-physiotherapy",
    name: "Mansfield Park Physiotherapy",
    type: "multi",
    town: "Medstead (nr Alton)",
    phone: "07341364504",
    website: "mansfieldparkphysio.co.uk",
    notes: "Small team, Mansfield Business Park. Physio + osteopathy",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "vfh-healthcare",
    name: "VFH Healthcare",
    type: "osteo",
    town: "Woking",
    phone: "07976315815",
    website: "vfhhealthcare.co.uk",
    notes: "Solo practitioner (Vanessa Hayward), osteopath + acupuncturist. Oriental Road",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "petersfield-osteopathy",
    name: "Petersfield Osteopathy",
    type: "osteo",
    town: "Petersfield",
    phone: "07766330489",
    website: "petersfieldosteopathy.com",
    notes: "Independent registered osteopath",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "encourage-movement",
    name: "Encourage Movement",
    type: "osteo",
    town: "Guildford",
    phone: "07479812264",
    website: "encouragemovement.co.uk",
    notes: "Based at Guildford Spectrum",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "align-osteopathic-clinic",
    name: "Align Osteopathic Clinic",
    type: "osteo",
    town: "Fleet",
    phone: "07568768667",
    phoneLandline: "01252621527",
    website: "alignosteoclinic.com",
    notes: "Near Fleet station, also cranial osteo + acupuncture",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "jw-osteopathy",
    name: "JW Osteopathy",
    type: "osteo",
    town: "Camberley / Yateley",
    phone: "07739072768",
    website: "jwosteopathy.co.uk",
    notes: "Solo (Jeremy Webb, 12 yrs), Basepoint Business Centre",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "lightwater-physiotherapy",
    name: "Lightwater Physiotherapy",
    type: "physio",
    town: "Lightwater",
    phone: "07876654321",
    website: "lightwaterphysiotherapy.co.uk",
    notes: "Solo (Shirley-Ann Walters, 30+ yrs), est. 2001",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },

  // --- Landline-only local leads ---
  {
    id: "ht-physio",
    name: "HT Physio",
    type: "physio",
    town: "Farnham",
    phone: "01252717529",
    website: "ht-physio.co.uk",
    notes: "Over-50s specialists. The Old Bakehouse, Clayton Court",
    tier: 2,
    signal: "local",
    batch: "farnham-landlines",
    batchLabel: "Farnham Landlines",
  },
  {
    id: "bourne-chiropractic-rehab",
    name: "Bourne Chiropractic & Rehab",
    type: "chiro",
    town: "Farnham",
    phone: "01252794037",
    website: "bournechiropracticclinic.co.uk",
    notes: "Small team (Lucy Vickers + massage therapist), The Bourne",
    tier: 2,
    signal: "local",
    batch: "farnham-landlines",
    batchLabel: "Farnham Landlines",
  },
  {
    id: "elstead-chiropractic-clinic",
    name: "Elstead Chiropractic Clinic",
    type: "chiro",
    town: "Farnham / Elstead",
    phone: "01252703633",
    website: "elsteadchiropractic.co.uk",
    notes: "Independent clinic serving Farnham area",
    tier: 2,
    signal: "local",
    batch: "farnham-landlines",
    batchLabel: "Farnham Landlines",
  },
  {
    id: "farnham-chiropractic-clinic",
    name: "Farnham Chiropractic Clinic",
    type: "chiro",
    town: "Farnham",
    phone: "01252710549",
    website: "farnhamclinic.co.uk",
    notes: "1 South Avenue, Heath End",
    tier: 2,
    signal: "local",
    batch: "farnham-landlines",
    batchLabel: "Farnham Landlines",
  },
  {
    id: "balanced-back-2-health",
    name: "Balanced Back 2 Health",
    type: "chiro",
    town: "Churt (nr Farnham)",
    phone: "01428892698",
    website: "balancedback2health.com",
    notes: "Small independent, Tilford Road, Churt",
    tier: 2,
    signal: "local",
    batch: "farnham-landlines",
    batchLabel: "Farnham Landlines",
  },
  {
    id: "farnham-osteopathic-practice",
    name: "Farnham Osteopathic Practice",
    type: "osteo",
    town: "Farnham",
    phone: "01252722912",
    website: "farnhamosteopaths.com",
    notes: "Est. 1989, solo (Chris Pinches, 38+ yrs). 2 Bishops Road",
    tier: 2,
    signal: "local",
    batch: "farnham-landlines",
    batchLabel: "Farnham Landlines",
  },
  {
    id: "meadowside-osteopathy",
    name: "Meadowside Osteopathy",
    type: "osteo",
    town: "Farnham",
    phone: "01252449435",
    website: "meadowsideosteopathy.co.uk",
    notes: "Hurlands Business Centre",
    tier: 2,
    signal: "local",
    batch: "farnham-landlines",
    batchLabel: "Farnham Landlines",
  },
  {
    id: "outline-health",
    name: "Outline Health",
    type: "osteo",
    town: "Ewshot (nr Farnham)",
    phone: "01252850814",
    website: "outlinehealth.com",
    notes: "Dare's Farm, Ewshot. Also Odiham clinic",
    tier: 2,
    signal: "local",
    batch: "farnham-landlines",
    batchLabel: "Farnham Landlines",
  },
  {
    id: "healthcare-hub",
    name: "Healthcare Hub",
    type: "multi",
    town: "Tongham (nr Farnham)",
    phone: "01252364956",
    website: "healthcarehub-surrey.com",
    notes: "Osteo, paediatric osteo, massage, pilates. The Granary, Tongham",
    tier: 2,
    signal: "local",
    batch: "farnham-landlines",
    batchLabel: "Farnham Landlines",
  },
  {
    id: "guildford-physiotherapy-sports-clinic",
    name: "Guildford Physiotherapy & Sports Clinic",
    type: "physio",
    town: "Guildford",
    phone: "01483976332",
    website: "guildfordphysio.org",
    notes: "Est. 80+ years, central Guildford. 6 Onslow Road",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "bevan-wilson-physiotherapy",
    name: "Bevan Wilson Physiotherapy",
    type: "physio",
    town: "Godalming / Guildford",
    phone: "01483424505",
    website: "bevanwilson.co.uk",
    notes: "20+ years, clinics in Godalming, Guildford, Wonersh",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "guildford-chiropractic-centre",
    name: "Guildford Chiropractic Centre",
    type: "chiro",
    town: "Guildford",
    phone: "01483562830",
    website: "guildfordchiropractic.co.uk",
    notes: "Est. 1953, Burchatts Farm Barn, Stoke Park",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "guildford-spine-centre",
    name: "Guildford Spine Centre",
    type: "chiro",
    town: "Guildford",
    phone: "01483808868",
    website: "spinecentreguildford.co.uk",
    notes: "10 yrs est., 229-235 High Street. Family-friendly",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "gw-osteopathy",
    name: "GW Osteopathy",
    type: "osteo",
    town: "Guildford",
    phone: "01483400207",
    website: "gwosteopathy.co.uk",
    notes: "Multiple practitioners, Wharf Road + Stoughton locations",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "care-for-health",
    name: "Care For Health",
    type: "multi",
    town: "Godalming",
    phone: "01483425544",
    website: "care-for-health.co.uk",
    notes: "Chiro + sports therapy + physio. Fox House, Station Approach",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "lucks-yard-clinic",
    name: "Luck's Yard Clinic",
    type: "multi",
    town: "Milford (nr Godalming)",
    phone: "01483527945",
    website: "lucksyardclinic.com",
    notes: "Award-winning, est. 2007. Chiro, physio, massage, nutrition",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "surrey-osteopathic-care",
    name: "Surrey Osteopathic Care",
    type: "osteo",
    town: "Godalming area",
    phone: "01483400207",
    website: "surreyosteopathiccare.co.uk",
    notes: "15+ years, cranial osteopathy specialist",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "cranleigh-osteopathic-practice",
    name: "Cranleigh Osteopathic Practice",
    type: "multi",
    town: "Cranleigh",
    phone: "01483268628",
    website: "cranleighosteo.co.uk",
    notes: "Est. 23+ years, The Old Bakery, 39 High Street. Osteo + physio",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "the-haslemere-clinic",
    name: "The Haslemere Clinic",
    type: "multi",
    town: "Haslemere",
    phone: "01428651067",
    website: "haslemereclinic.co.uk",
    notes: "Multi-disciplinary: 8 osteopaths, sports massage, counselling",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "haslemere-chiropractic-clinic",
    name: "Haslemere Chiropractic Clinic",
    type: "chiro",
    town: "Haslemere",
    phone: "01428642778",
    website: "haslemerechiropractic.com",
    notes: "Independent, 40 West Street",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "clinic-on-the-hill",
    name: "Clinic on the Hill",
    type: "osteo",
    town: "Haslemere",
    phone: "01428748525",
    website: "cliniconthehill.co.uk",
    notes: "Osteopathy + acupuncture, 2B High Street",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "heathercroft-osteopaths",
    name: "Heathercroft Osteopaths",
    type: "osteo",
    town: "Haslemere",
    phone: "01428643804",
    website: "heathercroftosteopaths.co.uk",
    notes: "Independent practice, Pine View Close",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "aldershot-physio",
    name: "Aldershot Physio",
    type: "multi",
    town: "Aldershot",
    phone: "02086856930",
    website: "aldershotphysio.co.uk",
    notes: "Physio, osteopathy, pilates. Independent clinic. Note: 0208 number unusual for area, may be shared booking service",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "farnborough-physio",
    name: "Farnborough Physio",
    type: "physio",
    town: "Farnborough",
    phone: "01252268501",
    website: "farnboroughphysio.co.uk",
    notes: "Modern private clinic, centre of Farnborough. Note: May be Surrey Physio brand - verify independence",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "fleet-osteopathic-clinic",
    name: "Fleet Osteopathic Clinic",
    type: "osteo",
    town: "Fleet",
    phone: "01252625359",
    website: "fleetosteopathicclinic.co.uk",
    notes: "Est. 1983, longest-standing in area. 6 Kings Road",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "hart-physio",
    name: "Hart Physio",
    type: "physio",
    town: "Fleet",
    phone: "01252811773",
    website: "hartphysio.com",
    notes: "Est. 25+ years, Kings Road, Fleet",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "thorpes-physiotherapy",
    name: "Thorpes Physiotherapy",
    type: "physio",
    town: "Sandhurst / Fleet",
    phone: "0127637670",
    website: "thorpesphysiotherapy.com",
    notes: "Award-winning, 2 locations: Sandhurst + Fleet",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "camberley-physiotherapy-sports-injury",
    name: "Camberley Physiotherapy & Sports Injury",
    type: "physio",
    town: "Camberley",
    phone: "01276459049",
    website: "camberleyphysiotherapy.co.uk",
    notes: "Attached to Upper Gordon Road Surgery",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "avenue-physiotherapy",
    name: "Avenue Physiotherapy",
    type: "physio",
    town: "Camberley",
    phone: "01276508408",
    website: "avenuephysio.co.uk",
    notes: "St Mary's Corner, 110 Frimley Road. Full-time reception",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "camberley-osteopathic-clinic",
    name: "Camberley Osteopathic Clinic",
    type: "osteo",
    town: "Camberley",
    phone: "01276683025",
    website: "camberleyosteopaths.co.uk",
    notes: "272 Gordon Avenue. Pain & injury specialists",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "osteopathic-consultancy",
    name: "Osteopathic Consultancy",
    type: "osteo",
    town: "Frimley Green",
    phone: "01276708954",
    website: "ostco.co.uk",
    notes: "Complex/chronic pain specialist, 3 Milden Close",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "lightwater-health-chiropractic",
    name: "Lightwater Health & Chiropractic",
    type: "chiro",
    town: "Lightwater",
    phone: "01276423434",
    website: "lightwaterhealthandchiropractic.com",
    notes: "1 The Square, Lightwater. Independent",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "victoria-clinic-woking",
    name: "Victoria Clinic Woking",
    type: "multi",
    town: "Woking",
    phone: "01483723688",
    website: "victoriachiropractic.co.uk",
    notes: "40+ years est., Chobham Road. Chiro, osteo, acupuncture",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "optimal-health-inspired",
    name: "Optimal Health Inspired",
    type: "chiro",
    town: "Send (nr Woking)",
    phone: "01483963713",
    website: "optimalhealthinspired.com",
    notes: "Milestone House, Portsmouth Road, Send",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "petersfield-physiotherapy-sports-injury",
    name: "Petersfield Physiotherapy & Sports Injury",
    type: "physio",
    town: "Liss (nr Petersfield)",
    phone: "01730267645",
    website: "petersfield-physio-clinic.co.uk",
    notes: "Based in Liss, near Hampshire/Surrey/Sussex borders",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "body-and-mind-physiotherapy",
    name: "Body And Mind Physiotherapy",
    type: "physio",
    town: "Petersfield",
    phone: "01730923842",
    website: "bodyandmindphysiotherapy.com",
    notes: "Sports injuries + women's health. Stanbridge Farm, Sussex Road",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "wenham-osteopathy",
    name: "Wenham Osteopathy",
    type: "osteo",
    town: "Rogate (nr Petersfield)",
    phone: "01730818320",
    website: "wenhamosteopathy.co.uk",
    notes: "Solo (Helen Mathieson), Wenham Manor Farmhouse",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "back-to-active-osteopathy",
    name: "Back to Active Osteopathy",
    type: "osteo",
    town: "Bordon",
    phone: "01420629059",
    website: "getbacktoactive.co.uk",
    notes: "Thorpe Court, Thorpe Close. Independent",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "medstead-osteopathic-practice",
    name: "Medstead Osteopathic Practice",
    type: "multi",
    town: "Medstead (nr Alton)",
    phone: "01420565644",
    website: "medsteadosteopath.co.uk",
    notes: "Osteo, chiro, acupuncture. Lymington Barns",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "alton-pain-clinic",
    name: "Alton Pain Clinic",
    type: "physio",
    town: "Alton",
    phone: "0142084487",
    website: "altonpainclinic.co.uk",
    notes: "First Floor, 70 High Street. MSK + injections",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },

  // ============================================================
  // HIRING RECEPTIONIST LEADS (signal: "hiring")
  // ============================================================

  // --- 1st Chiropractic Centres is in Yateley (local area) => hiring+local ---
  {
    id: "1st-chiropractic-centres",
    name: "1st Chiropractic Centres",
    type: "chiro",
    town: "Yateley, Hampshire",
    phone: "",
    website: "",
    notes: "Hiring Saturday Receptionist (4-5 hrs/wk) at 12.50/hr. Contact TBC. Local to Farnham area (GU46)",
    tier: 2,
    signal: "hiring+local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "prosport-physiotherapy",
    name: "ProSport Physiotherapy",
    type: "physio",
    town: "Huddersfield",
    phone: "",
    website: "",
    notes: "Hiring FT Receptionist. Contact TBC",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "romsey-physiotherapy-clinic",
    name: "Romsey Physiotherapy Clinic",
    type: "physio",
    town: "Romsey, Hampshire",
    phone: "",
    website: "",
    notes: "Hiring Receptionist/Admin (PT) at 13.25/hr. Contact TBC",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "lyfe-health-bristol-downend",
    name: "Lyfe Health Bristol Downend",
    type: "physio",
    town: "Bristol",
    phone: "",
    website: "",
    notes: "Hiring Sunday Receptionist (PT) at 12.71/hr. URGENT. Contact TBC",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "transform-wellness",
    name: "Transform Wellness",
    type: "wellness",
    town: "Epsom",
    phone: "",
    website: "",
    notes: "Hiring Front Desk Receptionist (PT). NEW listing. Contact TBC",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "physio-co-uk",
    name: "Physio.co.uk",
    type: "physio",
    town: "Manchester / Liverpool",
    phone: "",
    website: "",
    notes: "Hiring FT + PT Receptionists across 4+ sites. Contact: careers@physio.co.uk",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "southfields-physiotherapy",
    name: "Southfields Physiotherapy",
    type: "physio",
    town: "London SW18",
    phone: "",
    website: "",
    notes: "Hiring Admin & Customer Services Manager (FT). Contact: hr@southfieldsphysio.co.uk",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "cambridge-physiotherapy-clinic",
    name: "Cambridge Physiotherapy Clinic",
    type: "physio",
    town: "Cambridge",
    phone: "",
    website: "",
    notes: "Hiring Receptionist/Admin (PT, 3 days/wk). Contact TBC",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "the-treatment-room-group-uk",
    name: "The Treatment Room Group UK",
    type: "physio",
    town: "Newport",
    phone: "",
    website: "",
    notes: "Hiring Medical Admin/Receptionist (PT, 24 hrs/wk) at 12.60-13/hr. Contact TBC",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "begg-practice",
    name: "Begg Practice",
    type: "physio",
    town: "London SW11",
    phone: "",
    website: "",
    notes: "Hiring Reception/Admin (FT) at 12.21/hr. Contact TBC",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "bury-chiropractic",
    name: "Bury Chiropractic",
    type: "chiro",
    town: "Unsworth, Greater Manchester",
    phone: "",
    website: "",
    notes: "Hiring Front Desk / Sales / Customer Service (FT+PT). URGENT. Contact TBC",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "healthwise-chiropractic",
    name: "Healthwise Chiropractic",
    type: "chiro",
    town: "Hounslow",
    phone: "",
    website: "healthwisechiropracticclinic.com",
    notes: "Hiring Receptionist/Admin. Contact via website",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "emerald-chiropractic",
    name: "Emerald Chiropractic",
    type: "chiro",
    town: "Evesham",
    phone: "",
    website: "",
    notes: "Hiring PT Clinic Assistant (min 11 hrs/wk). Contact TBC",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "bodyevolve-spinal-health",
    name: "BODYEVOLVE Spinal Health",
    type: "chiro",
    town: "Hyde, Greater Manchester",
    phone: "",
    website: "",
    notes: "Hiring Chiro Assistant/Receptionist (PT, 1yr maternity cover) at 12.50/hr. Contact TBC",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "life-balance-chiropractic",
    name: "Life Balance Chiropractic",
    type: "chiro",
    town: "Poole, Dorset",
    phone: "",
    website: "",
    notes: "Hiring Chiro Assistant/Receptionist (PT) at 13.06/hr. Contact TBC",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "corehealth-chiropractic",
    name: "CoreHealth Chiropractic",
    type: "chiro",
    town: "Prestwick, Scotland",
    phone: "",
    website: "corehealthchiropractic.co.uk",
    notes: "Hiring Receptionist/Clinical Assistant (PT) at 12.25/hr",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "willow-chiropractic",
    name: "Willow Chiropractic",
    type: "chiro",
    town: "Clifton, Bristol",
    phone: "",
    website: "willowlife.co.uk",
    notes: "Hiring Front of House Receptionist",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "aberdeen-chiropractic-clinic",
    name: "Aberdeen Chiropractic Clinic",
    type: "chiro",
    town: "Aberdeen, Scotland",
    phone: "",
    website: "aberdeenchiropracticclinic.com",
    notes: "Hiring Receptionist/Clinical Assistant at 9.50-12/hr",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "st-johns-osteopathy-acupuncture",
    name: "St John's Osteopathy & Acupuncture",
    type: "osteo",
    town: "London NW8",
    phone: "",
    website: "sjoa.co.uk",
    notes: "Hiring Receptionist/Office Admin",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "london-school-of-osteopathy",
    name: "London School of Osteopathy",
    type: "osteo",
    town: "London (Bethnal Green)",
    phone: "",
    website: "",
    notes: "Hiring Clinical Receptionist. Contact: jobs@lso.ac.uk",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "pure-sports-medicine",
    name: "Pure Sports Medicine",
    type: "physio",
    town: "London (7 clinics)",
    phone: "",
    website: "puresportsmed.com",
    notes: "Hiring Clinical Receptionist (FT) at 23k/yr. 7 clinics across London",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },

  // ============================================================
  // AD-RUNNING LEADS (signal: "ads")
  // ============================================================

  // --- Halsa is in Godalming (local area) => ads+local ---
  {
    id: "halsa-chiropractic-physiotherapy",
    name: "Halsa Chiropractic & Physiotherapy",
    type: "multi",
    town: "Godalming, Surrey",
    phone: "01483937805",
    phoneLandline: "03331107000",
    website: "halsagroup.co.uk",
    notes: "Running Google Ads. 22-26 High Street. 4.8 stars (145 reviews). Paying for Google Ads + SEO",
    tier: 2,
    signal: "ads+local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "ldn-physio",
    name: "LDN Physio",
    type: "physio",
    town: "London (4 clinics)",
    phone: "02080586062",
    website: "ldnphysio.co.uk",
    notes: "Running Facebook/Instagram ads since Jul 2024. 4 clinics: Old Street, Hackney Central, Elephant & Castle, Kentish Town",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "ba-physiotherapy",
    name: "BA Physiotherapy",
    type: "physio",
    town: "Broughton Astley / Southam",
    phone: "01455285949",
    website: "baphysio.co.uk",
    notes: "Running Facebook/Instagram ads since Aug 2024. Two locations: Leicestershire + Warwickshire",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "osteo-and-physio",
    name: "Osteo and Physio",
    type: "multi",
    town: "Tiverton / Devon",
    phone: "03455577788",
    website: "osteoandphysio.co.uk",
    notes: "Running Facebook/Instagram/Messenger/Threads ads since May 2025. Multi-site group across Devon/Somerset. Free discovery consultations",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "er-physiotherapy",
    name: "ER Physiotherapy",
    type: "physio",
    town: "Aberdeen, Scotland",
    phone: "01224455759",
    website: "erphysiotherapy.co.uk",
    notes: "Running Facebook/Instagram/Messenger ads since May 2025. Award-winning team, 2 clinics in Aberdeen",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "davenport-house-clinic",
    name: "Davenport House Clinic",
    type: "multi",
    town: "Stalybridge, Greater Manchester",
    phone: "01613040117",
    website: "dhclinic.co.uk",
    notes: "Running Facebook/Instagram/Messenger ads since Nov 2025. Chiropody, podiatry and physiotherapy",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "wdc-physiotherapy-sports-injury-clinic",
    name: "WDC Physiotherapy & Sports Injury Clinic",
    type: "physio",
    town: "Southend-on-Sea, Essex",
    phone: "07758220963",
    phoneLandline: "01702613542",
    website: "wdcphysiotherapy.co.uk",
    notes: "Running Facebook/Instagram ads since Jul 2025. Sports injury clinic, also offers Pilates",
    tier: 2,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "cleve-chiropractic-physiotherapy-centre",
    name: "Cleve Chiropractic & Physiotherapy Centre",
    type: "multi",
    town: "Mangotsfield, Bristol",
    phone: "01179575388",
    website: "clevechiropractic.com",
    notes: "Running Facebook/Instagram ads since Jul 2022. Long-running advertiser (4+ years). Est. 2003. The Old School House, 20A Cossham Street",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "midlands-physiotherapy",
    name: "Midlands Physiotherapy",
    type: "physio",
    town: "Kidderminster, Worcestershire",
    phone: "01562754380",
    website: "midlandsphysio.co.uk",
    notes: "Running Facebook/Instagram ads since Mar 2024. 20+ years serving Worcestershire. Run by John Pryce",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "manchester-chiropractors",
    name: "Manchester Chiropractors",
    type: "chiro",
    town: "Manchester",
    phone: "07928072130",
    website: "manchesterchiropractors.co.uk",
    notes: "Running Facebook/Instagram/Messenger ads since Jun 2025. Limited-time offer ads (49.95). 28 Swan Street, Manchester",
    tier: 2,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "chichester-chiropractic-health-centre",
    name: "Chichester Chiropractic Health Centre",
    type: "chiro",
    town: "Chichester, West Sussex",
    phone: "01243913923",
    website: "chichesterchiropractor.co.uk",
    notes: "Running Facebook/Instagram ads since Jan 2025. Unit 5 The Courtyard, Vinnetrow Business Park",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "littlehampton-natural-health-centre",
    name: "Littlehampton Natural Health Centre",
    type: "osteo",
    town: "Littlehampton, West Sussex",
    phone: "01903734373",
    website: "lnhc.co.uk",
    notes: "Running Facebook/Instagram ads since Nov 2024. 10c Granville Road. Mon-Thu 9-6, Fri 9-1",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "worthing-osteopathic-wellbeing-clinic",
    name: "Worthing Osteopathic & Wellbeing Clinic",
    type: "osteo",
    town: "Worthing, West Sussex",
    phone: "01903366260",
    website: "worthingosteopathicwellbeing.co.uk",
    notes: "Running Facebook/Instagram/Messenger/Threads ads since Sep 2025. 140 South Street",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "sussex-back-pain-clinic",
    name: "Sussex Back Pain Clinic",
    type: "osteo",
    town: "Brighton & Hove",
    phone: "01273725667",
    website: "sussexbackpainclinic.co.uk",
    notes: "Running Facebook/Instagram/Messenger ads since Jun 2025. 58 New Church Road. Also IDD Therapy line 01273201866",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "msk-osteopath",
    name: "MSK Osteopath",
    type: "osteo",
    town: "Uppingham / Oakham, Rutland",
    phone: "07739828664",
    website: "mskosteopath.co.uk",
    notes: "Running Facebook/Instagram/Messenger ads since Nov 2019. Very long-running advertiser (6+ years). Osteopathy + acupuncture",
    tier: 2,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "the-rainham-osteopathic-clinic",
    name: "The Rainham Osteopathic Clinic",
    type: "osteo",
    town: "Rainham, Kent",
    phone: "01634386387",
    website: "rainhamosteo.co.uk",
    notes: "Running Facebook/Instagram ads. 2 Birling Avenue",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "revitalize-health-fitness-clinic",
    name: "Revitalize Health & Fitness Clinic",
    type: "multi",
    town: "Gravesend, Kent",
    phone: "01474356284",
    website: "revitalizeclinic.co.uk",
    notes: "Running Facebook/Instagram/Messenger ads since Aug 2025. 168 Windmill Street. Open 6am-8pm Mon-Sun",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "the-lancaster-clinic",
    name: "The Lancaster Clinic",
    type: "osteo",
    town: "Ware, Hertfordshire",
    phone: "01920464737",
    website: "lancasterosteopaths.com",
    notes: "Running Instagram ads. Sucklings Yard, Church St",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "mcr-injury-clinic",
    name: "MCR Injury Clinic",
    type: "physio",
    town: "Swinton, Manchester",
    phone: "01615231585",
    website: "mcrinjuryclinic.co.uk",
    notes: "Running Google Ads. 3 Moorside Road. 5.0 stars (497 reviews). High-intent ad spend",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "ideal-physio",
    name: "Ideal Physio",
    type: "physio",
    town: "Leeds",
    phone: "01132689326",
    website: "idealphysio.co.uk",
    notes: "Running Google Ads. Princes Exchange, Princes Square. 5.0 stars (53 reviews)",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
];

// --- Batch helper ---
export function getBatches(): { id: string; label: string; count: number }[] {
  const batchMap = new Map<string, { label: string; count: number }>();
  for (const lead of LEADS) {
    const existing = batchMap.get(lead.batch);
    if (existing) {
      existing.count++;
    } else {
      batchMap.set(lead.batch, { label: lead.batchLabel, count: 1 });
    }
  }
  return Array.from(batchMap.entries()).map(([id, data]) => ({ id, ...data }));
}
