export interface Lead {
  id: string;
  name: string;
  type: "physio" | "chiro" | "osteo" | "multi" | "wellness";
  town: string;
  phone: string;
  phoneLandline?: string;
  website?: string;
  notes: string;
  tier: 1 | 2 | 3;
  signal: "hiring" | "ads" | "local" | "hiring+local" | "ads+local";
  batch: string;
  batchLabel: string;
}

// Lead data — compiled from farnham-physio-leads.md, physio-leads.md, uk-physio-chiro-osteo-ad-leads.md
// + Google Maps scrape (18 Feb 2026): 79 leads across 6 cities
// Total leads after dedup: 186
export const LEADS: Lead[] = [
  // ============================================================
  // FARNHAM LOCAL LEADS (signal: "local")
  // ============================================================

  // --- Test lead (safe to call) ---
  {
    id: "test-lead-2",
    name: "TEST — CallingMode Test",
    type: "physio" as const,
    town: "Farnham",
    phone: "07700900000",
    notes: "BT test number — safe to dial, won't connect to anyone",
    tier: 1 as const,
    signal: "hiring" as const,
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },

  // --- Priority leads (mobile numbers) ---
  {
    id: "back-to-action-physiotherapy",
    name: "Back to Action Physiotherapy",
    type: "physio",
    town: "Farnham",
    phone: "07376067379",
    website: "backtoaction.co.uk",
    notes: "Solo practitioner, also does mobile physio covering Haslemere/Liphook/Liss. Based at IN2 Training gym",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "foster-chiropractic",
    name: "Foster Chiropractic",
    type: "chiro",
    town: "Farnham",
    phone: "07796018796",
    website: "fosterchiropractic.co.uk",
    notes: "Small independent clinic, 12 Old Compton Lane",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "coombe-house-clinic",
    name: "Coombe House Clinic",
    type: "osteo",
    town: "Farnham",
    phone: "07951133697",
    website: "coombehouseclinic.co.uk",
    notes: "Solo practitioner (Fleur Robertson), founded 2017. Cambridge House, East Street",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "charlotte-hunt-osteopaths",
    name: "Charlotte Hunt Osteopaths",
    type: "osteo",
    town: "Farnham (Lower Bourne)",
    phone: "07957563472",
    website: "charlottehuntosteopaths.co.uk",
    notes: "Solo practitioner, also has Coulsdon clinic. School hours Mon/Wed/Thu",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "farnham-natural-therapy-clinic",
    name: "Farnham Natural Therapy Clinic",
    type: "multi",
    town: "Farnham",
    phone: "07866141353",
    website: "farnhamnaturaltherapy.co.uk",
    notes: "Multi-therapist clinic, Hones Business Park",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "physio-in-motion",
    name: "Physio in Motion",
    type: "physio",
    town: "Farnham",
    phone: "07889890718",
    phoneLandline: "01252716611",
    website: "physioinmotion.co.uk",
    notes: "Solo practitioner (James Leyland), Waverley Clinic, East Street",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "midas-physiotherapy",
    name: "Midas Physiotherapy",
    type: "physio",
    town: "Farnham",
    phone: "07738074289",
    phoneLandline: "01252501373",
    website: "midasphysiotherapy.co.uk",
    notes: "Small clinic est. 2009, Farnham Business Park. Has both landline and mobile",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "back-on-track-chiropractic",
    name: "Back On Track Chiropractic",
    type: "chiro",
    town: "Farnham",
    phone: "07825777217",
    phoneLandline: "01252781133",
    website: "back-on-track.biz",
    notes: "Solo practitioner (Sukie Brockman), Alexander House, Waverley Lane",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "farnham-physiotherapy-sports-clinic",
    name: "Farnham Physiotherapy & Sports Clinic",
    type: "physio",
    town: "Farnham",
    phone: "07899544569",
    phoneLandline: "01252726479",
    website: "farnham-physiotherapy.co.uk",
    notes: "Established clinic, 20 Firgrove Hill. WhatsApp number available. 15+ yrs experience, open 6 days",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "dr-sean-chiropractor",
    name: "Dr Sean Chiropractor",
    type: "chiro",
    town: "Fleet",
    phone: "07942305554",
    website: "schiropractor.com",
    notes: "Solo practitioner, 27+ years experience. Stockton Avenue, Fleet",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "front-foot-physiotherapy",
    name: "Front Foot Physiotherapy",
    type: "physio",
    town: "Frimley Green",
    phone: "07413674694",
    website: "frontfootphysiotherapy.co.uk",
    notes: "Solo practitioner (Katherine), serves Camberley/Farnborough/Fleet. The Hatches",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "health-at-hart",
    name: "Health at Hart",
    type: "osteo",
    town: "Hartley Wintney",
    phone: "07921076758",
    website: "healthathart.co.uk",
    notes: "20+ years experience, cranial osteopathy. Old Post Office, High Street. Serves Fleet/Hook area",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "foundations-physio",
    name: "Foundations Physio",
    type: "physio",
    town: "Bordon / Farnham",
    phone: "07817495791",
    website: "foundationsphysio.co.uk",
    notes: "Covers Bordon, Aldershot, Farnham. Also has hydrotherapy",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "mansfield-park-physiotherapy",
    name: "Mansfield Park Physiotherapy",
    type: "multi",
    town: "Medstead (nr Alton)",
    phone: "07341364504",
    website: "mansfieldparkphysio.co.uk",
    notes: "Small team, Mansfield Business Park. Physio + osteopathy",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "vfh-healthcare",
    name: "VFH Healthcare",
    type: "osteo",
    town: "Woking",
    phone: "07976315815",
    website: "vfhhealthcare.co.uk",
    notes: "Solo practitioner (Vanessa Hayward), osteopath + acupuncturist. Oriental Road",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "petersfield-osteopathy",
    name: "Petersfield Osteopathy",
    type: "osteo",
    town: "Petersfield",
    phone: "07766330489",
    website: "petersfieldosteopathy.com",
    notes: "Independent registered osteopath",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "encourage-movement",
    name: "Encourage Movement",
    type: "osteo",
    town: "Guildford",
    phone: "07479812264",
    website: "encouragemovement.co.uk",
    notes: "Based at Guildford Spectrum",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "align-osteopathic-clinic",
    name: "Align Osteopathic Clinic",
    type: "osteo",
    town: "Fleet",
    phone: "07568768667",
    phoneLandline: "01252621527",
    website: "alignosteoclinic.com",
    notes: "Near Fleet station, also cranial osteo + acupuncture",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "jw-osteopathy",
    name: "JW Osteopathy",
    type: "osteo",
    town: "Camberley / Yateley",
    phone: "07739072768",
    website: "jwosteopathy.co.uk",
    notes: "Solo (Jeremy Webb, 12 yrs), Basepoint Business Centre",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },
  {
    id: "lightwater-physiotherapy",
    name: "Lightwater Physiotherapy",
    type: "physio",
    town: "Lightwater",
    phone: "07876654321",
    website: "lightwaterphysiotherapy.co.uk",
    notes: "Solo (Shirley-Ann Walters, 30+ yrs), est. 2001",
    tier: 1,
    signal: "local",
    batch: "farnham-mobiles",
    batchLabel: "Farnham Mobiles",
  },

  // --- Landline-only local leads ---
  {
    id: "ht-physio",
    name: "HT Physio",
    type: "physio",
    town: "Farnham",
    phone: "01252717529",
    website: "ht-physio.co.uk",
    notes: "Over-50s specialists. The Old Bakehouse, Clayton Court",
    tier: 2,
    signal: "local",
    batch: "farnham-landlines",
    batchLabel: "Farnham Landlines",
  },
  {
    id: "bourne-chiropractic-rehab",
    name: "Bourne Chiropractic & Rehab",
    type: "chiro",
    town: "Farnham",
    phone: "01252794037",
    website: "bournechiropracticclinic.co.uk",
    notes: "Small team (Lucy Vickers + massage therapist), The Bourne",
    tier: 2,
    signal: "local",
    batch: "farnham-landlines",
    batchLabel: "Farnham Landlines",
  },
  {
    id: "elstead-chiropractic-clinic",
    name: "Elstead Chiropractic Clinic",
    type: "chiro",
    town: "Farnham / Elstead",
    phone: "01252703633",
    website: "elsteadchiropractic.co.uk",
    notes: "Independent clinic serving Farnham area",
    tier: 2,
    signal: "local",
    batch: "farnham-landlines",
    batchLabel: "Farnham Landlines",
  },
  {
    id: "farnham-chiropractic-clinic",
    name: "Farnham Chiropractic Clinic",
    type: "chiro",
    town: "Farnham",
    phone: "01252710549",
    website: "farnhamclinic.co.uk",
    notes: "1 South Avenue, Heath End",
    tier: 2,
    signal: "local",
    batch: "farnham-landlines",
    batchLabel: "Farnham Landlines",
  },
  {
    id: "balanced-back-2-health",
    name: "Balanced Back 2 Health",
    type: "chiro",
    town: "Churt (nr Farnham)",
    phone: "01428892698",
    website: "balancedback2health.com",
    notes: "Small independent, Tilford Road, Churt",
    tier: 2,
    signal: "local",
    batch: "farnham-landlines",
    batchLabel: "Farnham Landlines",
  },
  {
    id: "farnham-osteopathic-practice",
    name: "Farnham Osteopathic Practice",
    type: "osteo",
    town: "Farnham",
    phone: "01252722912",
    website: "farnhamosteopaths.com",
    notes: "Est. 1989, solo (Chris Pinches, 38+ yrs). 2 Bishops Road",
    tier: 2,
    signal: "local",
    batch: "farnham-landlines",
    batchLabel: "Farnham Landlines",
  },
  {
    id: "meadowside-osteopathy",
    name: "Meadowside Osteopathy",
    type: "osteo",
    town: "Farnham",
    phone: "01252449435",
    website: "meadowsideosteopathy.co.uk",
    notes: "Hurlands Business Centre",
    tier: 2,
    signal: "local",
    batch: "farnham-landlines",
    batchLabel: "Farnham Landlines",
  },
  {
    id: "outline-health",
    name: "Outline Health",
    type: "osteo",
    town: "Ewshot (nr Farnham)",
    phone: "01252850814",
    website: "outlinehealth.com",
    notes: "Dare's Farm, Ewshot. Also Odiham clinic",
    tier: 2,
    signal: "local",
    batch: "farnham-landlines",
    batchLabel: "Farnham Landlines",
  },
  {
    id: "healthcare-hub",
    name: "Healthcare Hub",
    type: "multi",
    town: "Tongham (nr Farnham)",
    phone: "01252364956",
    website: "healthcarehub-surrey.com",
    notes: "Osteo, paediatric osteo, massage, pilates. The Granary, Tongham",
    tier: 2,
    signal: "local",
    batch: "farnham-landlines",
    batchLabel: "Farnham Landlines",
  },
  {
    id: "guildford-physiotherapy-sports-clinic",
    name: "Guildford Physiotherapy & Sports Clinic",
    type: "physio",
    town: "Guildford",
    phone: "01483976332",
    website: "guildfordphysio.org",
    notes: "Est. 80+ years, central Guildford. 6 Onslow Road",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "bevan-wilson-physiotherapy",
    name: "Bevan Wilson Physiotherapy",
    type: "physio",
    town: "Godalming / Guildford",
    phone: "01483424505",
    website: "bevanwilson.co.uk",
    notes: "20+ years, clinics in Godalming, Guildford, Wonersh",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "guildford-chiropractic-centre",
    name: "Guildford Chiropractic Centre",
    type: "chiro",
    town: "Guildford",
    phone: "01483562830",
    website: "guildfordchiropractic.co.uk",
    notes: "Est. 1953, Burchatts Farm Barn, Stoke Park",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "guildford-spine-centre",
    name: "Guildford Spine Centre",
    type: "chiro",
    town: "Guildford",
    phone: "01483808868",
    website: "spinecentreguildford.co.uk",
    notes: "10 yrs est., 229-235 High Street. Family-friendly",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "gw-osteopathy",
    name: "GW Osteopathy",
    type: "osteo",
    town: "Guildford",
    phone: "01483400207",
    website: "gwosteopathy.co.uk",
    notes: "Multiple practitioners, Wharf Road + Stoughton locations",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "care-for-health",
    name: "Care For Health",
    type: "multi",
    town: "Godalming",
    phone: "01483425544",
    website: "care-for-health.co.uk",
    notes: "Chiro + sports therapy + physio. Fox House, Station Approach",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "lucks-yard-clinic",
    name: "Luck's Yard Clinic",
    type: "multi",
    town: "Milford (nr Godalming)",
    phone: "01483527945",
    website: "lucksyardclinic.com",
    notes: "Award-winning, est. 2007. Chiro, physio, massage, nutrition",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "surrey-osteopathic-care",
    name: "Surrey Osteopathic Care",
    type: "osteo",
    town: "Godalming area",
    phone: "01483400207",
    website: "surreyosteopathiccare.co.uk",
    notes: "15+ years, cranial osteopathy specialist",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "cranleigh-osteopathic-practice",
    name: "Cranleigh Osteopathic Practice",
    type: "multi",
    town: "Cranleigh",
    phone: "01483268628",
    website: "cranleighosteo.co.uk",
    notes: "Est. 23+ years, The Old Bakery, 39 High Street. Osteo + physio",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "the-haslemere-clinic",
    name: "The Haslemere Clinic",
    type: "multi",
    town: "Haslemere",
    phone: "01428651067",
    website: "haslemereclinic.co.uk",
    notes: "Multi-disciplinary: 8 osteopaths, sports massage, counselling",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "haslemere-chiropractic-clinic",
    name: "Haslemere Chiropractic Clinic",
    type: "chiro",
    town: "Haslemere",
    phone: "01428642778",
    website: "haslemerechiropractic.com",
    notes: "Independent, 40 West Street",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "clinic-on-the-hill",
    name: "Clinic on the Hill",
    type: "osteo",
    town: "Haslemere",
    phone: "01428748525",
    website: "cliniconthehill.co.uk",
    notes: "Osteopathy + acupuncture, 2B High Street",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "heathercroft-osteopaths",
    name: "Heathercroft Osteopaths",
    type: "osteo",
    town: "Haslemere",
    phone: "01428643804",
    website: "heathercroftosteopaths.co.uk",
    notes: "Independent practice, Pine View Close",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "aldershot-physio",
    name: "Aldershot Physio",
    type: "multi",
    town: "Aldershot",
    phone: "02086856930",
    website: "aldershotphysio.co.uk",
    notes: "Physio, osteopathy, pilates. Independent clinic. Note: 0208 number unusual for area, may be shared booking service",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "farnborough-physio",
    name: "Farnborough Physio",
    type: "physio",
    town: "Farnborough",
    phone: "01252268501",
    website: "farnboroughphysio.co.uk",
    notes: "Modern private clinic, centre of Farnborough. Note: May be Surrey Physio brand - verify independence",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "fleet-osteopathic-clinic",
    name: "Fleet Osteopathic Clinic",
    type: "osteo",
    town: "Fleet",
    phone: "01252625359",
    website: "fleetosteopathicclinic.co.uk",
    notes: "Est. 1983, longest-standing in area. 6 Kings Road",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "hart-physio",
    name: "Hart Physio",
    type: "physio",
    town: "Fleet",
    phone: "01252811773",
    website: "hartphysio.com",
    notes: "Est. 25+ years, Kings Road, Fleet",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "thorpes-physiotherapy",
    name: "Thorpes Physiotherapy",
    type: "physio",
    town: "Sandhurst / Fleet",
    phone: "0127637670",
    website: "thorpesphysiotherapy.com",
    notes: "Award-winning, 2 locations: Sandhurst + Fleet",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "camberley-physiotherapy-sports-injury",
    name: "Camberley Physiotherapy & Sports Injury",
    type: "physio",
    town: "Camberley",
    phone: "01276459049",
    website: "camberleyphysiotherapy.co.uk",
    notes: "Attached to Upper Gordon Road Surgery",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "avenue-physiotherapy",
    name: "Avenue Physiotherapy",
    type: "physio",
    town: "Camberley",
    phone: "01276508408",
    website: "avenuephysio.co.uk",
    notes: "St Mary's Corner, 110 Frimley Road. Full-time reception",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "camberley-osteopathic-clinic",
    name: "Camberley Osteopathic Clinic",
    type: "osteo",
    town: "Camberley",
    phone: "01276683025",
    website: "camberleyosteopaths.co.uk",
    notes: "272 Gordon Avenue. Pain & injury specialists",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "osteopathic-consultancy",
    name: "Osteopathic Consultancy",
    type: "osteo",
    town: "Frimley Green",
    phone: "01276708954",
    website: "ostco.co.uk",
    notes: "Complex/chronic pain specialist, 3 Milden Close",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "lightwater-health-chiropractic",
    name: "Lightwater Health & Chiropractic",
    type: "chiro",
    town: "Lightwater",
    phone: "01276423434",
    website: "lightwaterhealthandchiropractic.com",
    notes: "1 The Square, Lightwater. Independent",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "victoria-clinic-woking",
    name: "Victoria Clinic Woking",
    type: "multi",
    town: "Woking",
    phone: "01483723688",
    website: "victoriachiropractic.co.uk",
    notes: "40+ years est., Chobham Road. Chiro, osteo, acupuncture",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "optimal-health-inspired",
    name: "Optimal Health Inspired",
    type: "chiro",
    town: "Send (nr Woking)",
    phone: "01483963713",
    website: "optimalhealthinspired.com",
    notes: "Milestone House, Portsmouth Road, Send",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "petersfield-physiotherapy-sports-injury",
    name: "Petersfield Physiotherapy & Sports Injury",
    type: "physio",
    town: "Liss (nr Petersfield)",
    phone: "01730267645",
    website: "petersfield-physio-clinic.co.uk",
    notes: "Based in Liss, near Hampshire/Surrey/Sussex borders",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "body-and-mind-physiotherapy",
    name: "Body And Mind Physiotherapy",
    type: "physio",
    town: "Petersfield",
    phone: "01730923842",
    website: "bodyandmindphysiotherapy.com",
    notes: "Sports injuries + women's health. Stanbridge Farm, Sussex Road",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "wenham-osteopathy",
    name: "Wenham Osteopathy",
    type: "osteo",
    town: "Rogate (nr Petersfield)",
    phone: "01730818320",
    website: "wenhamosteopathy.co.uk",
    notes: "Solo (Helen Mathieson), Wenham Manor Farmhouse",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "back-to-active-osteopathy",
    name: "Back to Active Osteopathy",
    type: "osteo",
    town: "Bordon",
    phone: "01420629059",
    website: "getbacktoactive.co.uk",
    notes: "Thorpe Court, Thorpe Close. Independent",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "medstead-osteopathic-practice",
    name: "Medstead Osteopathic Practice",
    type: "multi",
    town: "Medstead (nr Alton)",
    phone: "01420565644",
    website: "medsteadosteopath.co.uk",
    notes: "Osteo, chiro, acupuncture. Lymington Barns",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "alton-pain-clinic",
    name: "Alton Pain Clinic",
    type: "physio",
    town: "Alton",
    phone: "0142084487",
    website: "altonpainclinic.co.uk",
    notes: "First Floor, 70 High Street. MSK + injections",
    tier: 2,
    signal: "local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },

  // ============================================================
  // HIRING RECEPTIONIST LEADS (signal: "hiring")
  // ============================================================

  // --- 1st Chiropractic Centres is in Yateley (local area) => hiring+local ---
  {
    id: "1st-chiropractic-centres",
    name: "1st Chiropractic Centres",
    type: "chiro",
    town: "Yateley, Hampshire",
    phone: "",
    website: "",
    notes: "Hiring Saturday Receptionist (4-5 hrs/wk) at 12.50/hr. Contact TBC. Local to Farnham area (GU46)",
    tier: 2,
    signal: "hiring+local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "prosport-physiotherapy",
    name: "ProSport Physiotherapy",
    type: "physio",
    town: "Huddersfield",
    phone: "",
    website: "",
    notes: "Hiring FT Receptionist. Contact TBC",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "romsey-physiotherapy-clinic",
    name: "Romsey Physiotherapy Clinic",
    type: "physio",
    town: "Romsey, Hampshire",
    phone: "",
    website: "",
    notes: "Hiring Receptionist/Admin (PT) at 13.25/hr. Contact TBC",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "lyfe-health-bristol-downend",
    name: "Lyfe Health Bristol Downend",
    type: "physio",
    town: "Bristol",
    phone: "",
    website: "",
    notes: "Hiring Sunday Receptionist (PT) at 12.71/hr. URGENT. Contact TBC",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "transform-wellness",
    name: "Transform Wellness",
    type: "wellness",
    town: "Epsom",
    phone: "",
    website: "",
    notes: "Hiring Front Desk Receptionist (PT). NEW listing. Contact TBC",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "physio-co-uk",
    name: "Physio.co.uk",
    type: "physio",
    town: "Manchester / Liverpool",
    phone: "",
    website: "",
    notes: "Hiring FT + PT Receptionists across 4+ sites. Contact: careers@physio.co.uk",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "southfields-physiotherapy",
    name: "Southfields Physiotherapy",
    type: "physio",
    town: "London SW18",
    phone: "",
    website: "",
    notes: "Hiring Admin & Customer Services Manager (FT). Contact: hr@southfieldsphysio.co.uk",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "cambridge-physiotherapy-clinic",
    name: "Cambridge Physiotherapy Clinic",
    type: "physio",
    town: "Cambridge",
    phone: "",
    website: "",
    notes: "Hiring Receptionist/Admin (PT, 3 days/wk). Contact TBC",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "the-treatment-room-group-uk",
    name: "The Treatment Room Group UK",
    type: "physio",
    town: "Newport",
    phone: "",
    website: "",
    notes: "Hiring Medical Admin/Receptionist (PT, 24 hrs/wk) at 12.60-13/hr. Contact TBC",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "begg-practice",
    name: "Begg Practice",
    type: "physio",
    town: "London SW11",
    phone: "",
    website: "",
    notes: "Hiring Reception/Admin (FT) at 12.21/hr. Contact TBC",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "bury-chiropractic",
    name: "Bury Chiropractic",
    type: "chiro",
    town: "Unsworth, Greater Manchester",
    phone: "",
    website: "",
    notes: "Hiring Front Desk / Sales / Customer Service (FT+PT). URGENT. Contact TBC",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "healthwise-chiropractic",
    name: "Healthwise Chiropractic",
    type: "chiro",
    town: "Hounslow",
    phone: "",
    website: "healthwisechiropracticclinic.com",
    notes: "Hiring Receptionist/Admin. Contact via website",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "emerald-chiropractic",
    name: "Emerald Chiropractic",
    type: "chiro",
    town: "Evesham",
    phone: "",
    website: "",
    notes: "Hiring PT Clinic Assistant (min 11 hrs/wk). Contact TBC",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "bodyevolve-spinal-health",
    name: "BODYEVOLVE Spinal Health",
    type: "chiro",
    town: "Hyde, Greater Manchester",
    phone: "",
    website: "",
    notes: "Hiring Chiro Assistant/Receptionist (PT, 1yr maternity cover) at 12.50/hr. Contact TBC",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "life-balance-chiropractic",
    name: "Life Balance Chiropractic",
    type: "chiro",
    town: "Poole, Dorset",
    phone: "",
    website: "",
    notes: "Hiring Chiro Assistant/Receptionist (PT) at 13.06/hr. Contact TBC",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "corehealth-chiropractic",
    name: "CoreHealth Chiropractic",
    type: "chiro",
    town: "Prestwick, Scotland",
    phone: "",
    website: "corehealthchiropractic.co.uk",
    notes: "Hiring Receptionist/Clinical Assistant (PT) at 12.25/hr",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "willow-chiropractic",
    name: "Willow Chiropractic",
    type: "chiro",
    town: "Clifton, Bristol",
    phone: "",
    website: "willowlife.co.uk",
    notes: "Hiring Front of House Receptionist",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "aberdeen-chiropractic-clinic",
    name: "Aberdeen Chiropractic Clinic",
    type: "chiro",
    town: "Aberdeen, Scotland",
    phone: "",
    website: "aberdeenchiropracticclinic.com",
    notes: "Hiring Receptionist/Clinical Assistant at 9.50-12/hr",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "st-johns-osteopathy-acupuncture",
    name: "St John's Osteopathy & Acupuncture",
    type: "osteo",
    town: "London NW8",
    phone: "",
    website: "sjoa.co.uk",
    notes: "Hiring Receptionist/Office Admin",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "london-school-of-osteopathy",
    name: "London School of Osteopathy",
    type: "osteo",
    town: "London (Bethnal Green)",
    phone: "",
    website: "",
    notes: "Hiring Clinical Receptionist. Contact: jobs@lso.ac.uk",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },
  {
    id: "pure-sports-medicine",
    name: "Pure Sports Medicine",
    type: "physio",
    town: "London (7 clinics)",
    phone: "",
    website: "puresportsmed.com",
    notes: "Hiring Clinical Receptionist (FT) at 23k/yr. 7 clinics across London",
    tier: 3,
    signal: "hiring",
    batch: "indeed-hiring",
    batchLabel: "Indeed Hiring",
  },

  // ============================================================
  // AD-RUNNING LEADS (signal: "ads")
  // ============================================================

  // --- Halsa is in Godalming (local area) => ads+local ---
  {
    id: "halsa-chiropractic-physiotherapy",
    name: "Halsa Chiropractic & Physiotherapy",
    type: "multi",
    town: "Godalming, Surrey",
    phone: "01483937805",
    phoneLandline: "03331107000",
    website: "halsagroup.co.uk",
    notes: "Running Google Ads. 22-26 High Street. 4.8 stars (145 reviews). Paying for Google Ads + SEO",
    tier: 2,
    signal: "ads+local",
    batch: "wider-surrey",
    batchLabel: "Wider Surrey",
  },
  {
    id: "ldn-physio",
    name: "LDN Physio",
    type: "physio",
    town: "London (4 clinics)",
    phone: "02080586062",
    website: "ldnphysio.co.uk",
    notes: "Running Facebook/Instagram ads since Jul 2024. 4 clinics: Old Street, Hackney Central, Elephant & Castle, Kentish Town",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "ba-physiotherapy",
    name: "BA Physiotherapy",
    type: "physio",
    town: "Broughton Astley / Southam",
    phone: "01455285949",
    website: "baphysio.co.uk",
    notes: "Running Facebook/Instagram ads since Aug 2024. Two locations: Leicestershire + Warwickshire",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "osteo-and-physio",
    name: "Osteo and Physio",
    type: "multi",
    town: "Tiverton / Devon",
    phone: "03455577788",
    website: "osteoandphysio.co.uk",
    notes: "Running Facebook/Instagram/Messenger/Threads ads since May 2025. Multi-site group across Devon/Somerset. Free discovery consultations",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "er-physiotherapy",
    name: "ER Physiotherapy",
    type: "physio",
    town: "Aberdeen, Scotland",
    phone: "01224455759",
    website: "erphysiotherapy.co.uk",
    notes: "Running Facebook/Instagram/Messenger ads since May 2025. Award-winning team, 2 clinics in Aberdeen",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "davenport-house-clinic",
    name: "Davenport House Clinic",
    type: "multi",
    town: "Stalybridge, Greater Manchester",
    phone: "01613040117",
    website: "dhclinic.co.uk",
    notes: "Running Facebook/Instagram/Messenger ads since Nov 2025. Chiropody, podiatry and physiotherapy",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "wdc-physiotherapy-sports-injury-clinic",
    name: "WDC Physiotherapy & Sports Injury Clinic",
    type: "physio",
    town: "Southend-on-Sea, Essex",
    phone: "07758220963",
    phoneLandline: "01702613542",
    website: "wdcphysiotherapy.co.uk",
    notes: "Running Facebook/Instagram ads since Jul 2025. Sports injury clinic, also offers Pilates",
    tier: 2,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "cleve-chiropractic-physiotherapy-centre",
    name: "Cleve Chiropractic & Physiotherapy Centre",
    type: "multi",
    town: "Mangotsfield, Bristol",
    phone: "01179575388",
    website: "clevechiropractic.com",
    notes: "Running Facebook/Instagram ads since Jul 2022. Long-running advertiser (4+ years). Est. 2003. The Old School House, 20A Cossham Street",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "midlands-physiotherapy",
    name: "Midlands Physiotherapy",
    type: "physio",
    town: "Kidderminster, Worcestershire",
    phone: "01562754380",
    website: "midlandsphysio.co.uk",
    notes: "Running Facebook/Instagram ads since Mar 2024. 20+ years serving Worcestershire. Run by John Pryce",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "manchester-chiropractors",
    name: "Manchester Chiropractors",
    type: "chiro",
    town: "Manchester",
    phone: "07928072130",
    website: "manchesterchiropractors.co.uk",
    notes: "Running Facebook/Instagram/Messenger ads since Jun 2025. Limited-time offer ads (49.95). 28 Swan Street, Manchester",
    tier: 2,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "chichester-chiropractic-health-centre",
    name: "Chichester Chiropractic Health Centre",
    type: "chiro",
    town: "Chichester, West Sussex",
    phone: "01243913923",
    website: "chichesterchiropractor.co.uk",
    notes: "Running Facebook/Instagram ads since Jan 2025. Unit 5 The Courtyard, Vinnetrow Business Park",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "littlehampton-natural-health-centre",
    name: "Littlehampton Natural Health Centre",
    type: "osteo",
    town: "Littlehampton, West Sussex",
    phone: "01903734373",
    website: "lnhc.co.uk",
    notes: "Running Facebook/Instagram ads since Nov 2024. 10c Granville Road. Mon-Thu 9-6, Fri 9-1",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "worthing-osteopathic-wellbeing-clinic",
    name: "Worthing Osteopathic & Wellbeing Clinic",
    type: "osteo",
    town: "Worthing, West Sussex",
    phone: "01903366260",
    website: "worthingosteopathicwellbeing.co.uk",
    notes: "Running Facebook/Instagram/Messenger/Threads ads since Sep 2025. 140 South Street",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "sussex-back-pain-clinic",
    name: "Sussex Back Pain Clinic",
    type: "osteo",
    town: "Brighton & Hove",
    phone: "01273725667",
    website: "sussexbackpainclinic.co.uk",
    notes: "Running Facebook/Instagram/Messenger ads since Jun 2025. 58 New Church Road. Also IDD Therapy line 01273201866",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "msk-osteopath",
    name: "MSK Osteopath",
    type: "osteo",
    town: "Uppingham / Oakham, Rutland",
    phone: "07739828664",
    website: "mskosteopath.co.uk",
    notes: "Running Facebook/Instagram/Messenger ads since Nov 2019. Very long-running advertiser (6+ years). Osteopathy + acupuncture",
    tier: 2,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "the-rainham-osteopathic-clinic",
    name: "The Rainham Osteopathic Clinic",
    type: "osteo",
    town: "Rainham, Kent",
    phone: "01634386387",
    website: "rainhamosteo.co.uk",
    notes: "Running Facebook/Instagram ads. 2 Birling Avenue",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "revitalize-health-fitness-clinic",
    name: "Revitalize Health & Fitness Clinic",
    type: "multi",
    town: "Gravesend, Kent",
    phone: "01474356284",
    website: "revitalizeclinic.co.uk",
    notes: "Running Facebook/Instagram/Messenger ads since Aug 2025. 168 Windmill Street. Open 6am-8pm Mon-Sun",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "the-lancaster-clinic",
    name: "The Lancaster Clinic",
    type: "osteo",
    town: "Ware, Hertfordshire",
    phone: "01920464737",
    website: "lancasterosteopaths.com",
    notes: "Running Instagram ads. Sucklings Yard, Church St",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "mcr-injury-clinic",
    name: "MCR Injury Clinic",
    type: "physio",
    town: "Swinton, Manchester",
    phone: "01615231585",
    website: "mcrinjuryclinic.co.uk",
    notes: "Running Google Ads. 3 Moorside Road. 5.0 stars (497 reviews). High-intent ad spend",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },
  {
    id: "ideal-physio",
    name: "Ideal Physio",
    type: "physio",
    town: "Leeds",
    phone: "01132689326",
    website: "idealphysio.co.uk",
    notes: "Running Google Ads. Princes Exchange, Princes Square. 5.0 stars (53 reviews)",
    tier: 3,
    signal: "ads",
    batch: "running-ads",
    batchLabel: "Running Ads",
  },

  // ============================================================
  // BRISTOL PHYSIOS — Max's test batch
  // ============================================================

  {
    id: "bristol-1",
    name: "Bristol Physio",
    type: "physio" as const,
    town: "Bristol",
    phone: "01179237506",
    notes: "Google Maps lead",
    tier: 2 as const,
    signal: "local" as const,
    batch: "bristol-physios",
    batchLabel: "Bristol Physios",
  },
  {
    id: "bristol-2",
    name: "The Physio Clinic Bristol",
    type: "physio" as const,
    town: "Bristol",
    phone: "01454540066",
    notes: "Google Maps lead",
    tier: 2 as const,
    signal: "local" as const,
    batch: "bristol-physios",
    batchLabel: "Bristol Physios",
  },
  {
    id: "bristol-3",
    name: "Comfort Health",
    type: "physio" as const,
    town: "Bristol",
    phone: "01173731053",
    notes: "Google Maps lead",
    tier: 2 as const,
    signal: "local" as const,
    batch: "bristol-physios",
    batchLabel: "Bristol Physios",
  },
  {
    id: "bristol-4",
    name: "Rise Physiotherapy",
    type: "physio" as const,
    town: "Bristol",
    phone: "07881912334",
    notes: "Google Maps lead",
    tier: 2 as const,
    signal: "local" as const,
    batch: "bristol-physios",
    batchLabel: "Bristol Physios",
  },
  {
    id: "bristol-5",
    name: "ProActive Physiotherapy",
    type: "physio" as const,
    town: "Bristol",
    phone: "01174624177",
    notes: "Google Maps lead",
    tier: 2 as const,
    signal: "local" as const,
    batch: "bristol-physios",
    batchLabel: "Bristol Physios",
  },

  // ============================================================
  // GOOGLE MAPS SCRAPE — Local mobiles (18 Feb 2026)
  // ============================================================

  // --- GUILDFORD MOBILES (12 leads) ---
  {
    id: "pace-physiotherapy-sports-massage",
    name: "PACE Physiotherapy & Sports Massage",
    type: "physio",
    town: "Guildford",
    phone: "07877624988",
    website: "pacetherapies.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 36 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "guildford-mobiles",
    batchLabel: "Guildford Mobiles",
  },
  {
    id: "nina-robinson-physiotherapist",
    name: "Nina Robinson Physiotherapist",
    type: "physio",
    town: "Guildford",
    phone: "07966176083",
    website: "ninarobinsonphysio.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 24 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "guildford-mobiles",
    batchLabel: "Guildford Mobiles",
  },
  {
    id: "guildford-and-godalming-physio",
    name: "Guildford and Godalming Physio",
    type: "physio",
    town: "Guildford",
    phone: "07859981103",
    website: "guildfordgodalmingphysio.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 41 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "guildford-mobiles",
    batchLabel: "Guildford Mobiles",
  },
  {
    id: "reforge-rehabilitation",
    name: "Reforge Rehabilitation",
    type: "physio",
    town: "Guildford",
    phone: "07805609038",
    website: "reforgerehabilitation.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 16 reviews - Sports injury clinic",
    tier: 2,
    signal: "local",
    batch: "guildford-mobiles",
    batchLabel: "Guildford Mobiles",
  },
  {
    id: "life-made-simple-physiotherapy",
    name: "Life Made Simple Physiotherapy",
    type: "physio",
    town: "Guildford",
    phone: "07309272555",
    website: "lifemadesimple.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 24 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "guildford-mobiles",
    batchLabel: "Guildford Mobiles",
  },
  {
    id: "ds-sports-therapy",
    name: "DS Sports Therapy",
    type: "physio",
    town: "Guildford",
    phone: "07871476651",
    website: "dssportstherapy.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 50 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "guildford-mobiles",
    batchLabel: "Guildford Mobiles",
  },
  {
    id: "flair-physiotherapy",
    name: "Flair Physiotherapy",
    type: "physio",
    town: "Guildford",
    phone: "07868831034",
    website: "flairphysio.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 3 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "guildford-mobiles",
    batchLabel: "Guildford Mobiles",
  },
  {
    id: "ross-therapy-guildford",
    name: "Ross Therapy Guildford",
    type: "physio",
    town: "Guildford",
    phone: "07983148551",
    website: "rosstherapy.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 2 reviews - Sports injury clinic",
    tier: 2,
    signal: "local",
    batch: "guildford-mobiles",
    batchLabel: "Guildford Mobiles",
  },
  {
    id: "mjm-physiotherapy",
    name: "MJM Physiotherapy",
    type: "physio",
    town: "Guildford",
    phone: "07941887162",
    website: "mjm-uk.com",
    notes: "From Google Maps scrape - 5.0 stars - 21 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "guildford-mobiles",
    batchLabel: "Guildford Mobiles",
  },
  {
    id: "physioreach",
    name: "Physioreach",
    type: "physio",
    town: "Guildford",
    phone: "07791611717",
    website: "physioreach.co.uk",
    notes: "From Google Maps scrape - Physical Therapy Clinic",
    tier: 2,
    signal: "local",
    batch: "guildford-mobiles",
    batchLabel: "Guildford Mobiles",
  },
  {
    id: "first-place-physiotherapy",
    name: "First Place Physiotherapy",
    type: "physio",
    town: "Guildford",
    phone: "07791731485",
    website: "firstplacephysiotherapy.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 8 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "guildford-mobiles",
    batchLabel: "Guildford Mobiles",
  },
  {
    id: "jo-coulter-physiotherapy",
    name: "Jo Coulter Physiotherapy",
    type: "physio",
    town: "Guildford",
    phone: "07855942486",
    website: "jocoulter.com",
    notes: "From Google Maps scrape - 5.0 stars - 16 reviews - Physical Therapy Clinic",
    tier: 2,
    signal: "local",
    batch: "guildford-mobiles",
    batchLabel: "Guildford Mobiles",
  },

  // --- WOKING/FARNHAM MOBILES (11 leads) ---
  {
    id: "physiotherapy-home-visits-physioway-rehabhome",
    name: "Physiotherapy Home visits -Physioway Rehab@Home.",
    type: "physio",
    town: "Woking/Farnham",
    phone: "07727653407",
    website: "physiowayrehab.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 20 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "woking-farnham-mobiles",
    batchLabel: "Woking/Farnham Mobiles",
  },
  {
    id: "mobilise-sports-injury-clinic",
    name: "Mobilise Sports Injury Clinic",
    type: "physio",
    town: "Woking/Farnham",
    phone: "07938877106",
    website: "mobilisesportsinjuryclinic.com",
    notes: "From Google Maps scrape - 5.0 stars - 77 reviews - Sports injury clinic",
    tier: 2,
    signal: "local",
    batch: "woking-farnham-mobiles",
    batchLabel: "Woking/Farnham Mobiles",
  },
  {
    id: "refit",
    name: "Re:fit",
    type: "physio",
    town: "Woking/Farnham",
    phone: "07876751010",
    website: "re-fit.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 2 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "woking-farnham-mobiles",
    batchLabel: "Woking/Farnham Mobiles",
  },
  {
    id: "bearwood-physiotherapy-farnham-gu9",
    name: "Bearwood Physiotherapy - Farnham - GU9",
    type: "physio",
    town: "Woking/Farnham",
    phone: "07986726346",
    website: "bearwoodphysiotherapy.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 1 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "woking-farnham-mobiles",
    batchLabel: "Woking/Farnham Mobiles",
  },
  {
    id: "ef-sport-therapies",
    name: "EF Sport Therapies",
    type: "physio",
    town: "Woking/Farnham",
    phone: "07537103313",
    website: "efsporttherapies.co.uk",
    notes: "From Google Maps scrape - 4.9 stars - 30 reviews - Sports injury clinic",
    tier: 2,
    signal: "local",
    batch: "woking-farnham-mobiles",
    batchLabel: "Woking/Farnham Mobiles",
  },
  {
    id: "stride-forward-physiotherapy",
    name: "Stride Forward Physiotherapy",
    type: "physio",
    town: "Woking/Farnham",
    phone: "07964785164",
    website: "strideforwardphysiotherapy.com",
    notes: "From Google Maps scrape - 5.0 stars - 22 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "woking-farnham-mobiles",
    batchLabel: "Woking/Farnham Mobiles",
  },
  {
    id: "rehab-train-perform",
    name: "Rehab Train Perform",
    type: "physio",
    town: "Woking/Farnham",
    phone: "07410978219",
    website: "rehabtrainperform.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 24 reviews - Fitness centre",
    tier: 2,
    signal: "local",
    batch: "woking-farnham-mobiles",
    batchLabel: "Woking/Farnham Mobiles",
  },
  {
    id: "kaizen-health-and-performance",
    name: "Kaizen Health and Performance",
    type: "physio",
    town: "Woking/Farnham",
    phone: "07577295384",
    notes: "From Google Maps scrape - Gym",
    tier: 2,
    signal: "local",
    batch: "woking-farnham-mobiles",
    batchLabel: "Woking/Farnham Mobiles",
  },
  {
    id: "victoria-s-physio",
    name: "Victoria S Physio",
    type: "physio",
    town: "Woking/Farnham",
    phone: "07908483525",
    notes: "From Google Maps scrape - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "woking-farnham-mobiles",
    batchLabel: "Woking/Farnham Mobiles",
  },
  {
    id: "local-physios-woking",
    name: "Local Physios Woking",
    type: "physio",
    town: "Woking/Farnham",
    phone: "07799135532",
    website: "localphysios.com",
    notes: "From Google Maps scrape - Physical Therapy Clinic",
    tier: 2,
    signal: "local",
    batch: "woking-farnham-mobiles",
    batchLabel: "Woking/Farnham Mobiles",
  },
  {
    id: "studyo-physiotherapy",
    name: "Studyo Physiotherapy",
    type: "physio",
    town: "Woking/Farnham",
    phone: "07894068956",
    notes: "From Google Maps scrape - 5.0 stars - 4 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "woking-farnham-mobiles",
    batchLabel: "Woking/Farnham Mobiles",
  },

  // --- BASINGSTOKE MOBILES (15 leads) ---
  {
    id: "lakky-physiotherapy-sports-injury-clinic",
    name: "Lakky Physiotherapy & Sports Injury Clinic",
    type: "physio",
    town: "Basingstoke",
    phone: "07894866633",
    website: "lakkyphysio.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 416 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "basingstoke-mobiles",
    batchLabel: "Basingstoke Mobiles",
  },
  {
    id: "pk-physio-basingstoke",
    name: "PK Physio Basingstoke",
    type: "physio",
    town: "Basingstoke",
    phone: "07853588465",
    website: "pkphysio.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 76 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "basingstoke-mobiles",
    batchLabel: "Basingstoke Mobiles",
  },
  {
    id: "the-optimal-sports-therapy-centre",
    name: "The Optimal Sports Therapy Centre",
    type: "physio",
    town: "Basingstoke",
    phone: "07876351562",
    website: "optimalcentre.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 41 reviews - Physical Therapy Clinic",
    tier: 2,
    signal: "local",
    batch: "basingstoke-mobiles",
    batchLabel: "Basingstoke Mobiles",
  },
  {
    id: "rutledge-sports-therapy",
    name: "Rutledge Sports Therapy",
    type: "physio",
    town: "Basingstoke",
    phone: "07961080577",
    website: "rutledge-sports-therapy.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 21 reviews - Physical Therapy Clinic",
    tier: 2,
    signal: "local",
    batch: "basingstoke-mobiles",
    batchLabel: "Basingstoke Mobiles",
  },
  {
    id: "pal-square-physio-limited",
    name: "PAL SQUARE PHYSIO LIMITED",
    type: "physio",
    town: "Basingstoke",
    phone: "07958671909",
    website: "palsquarephysiotherapy.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 5 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "basingstoke-mobiles",
    batchLabel: "Basingstoke Mobiles",
  },
  {
    id: "mark-randall-physiotherapy",
    name: "Mark Randall Physiotherapy",
    type: "physio",
    town: "Basingstoke",
    phone: "07971972779",
    website: "markrandallphysiotherapy.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 1 reviews - Physical Therapy Clinic",
    tier: 2,
    signal: "local",
    batch: "basingstoke-mobiles",
    batchLabel: "Basingstoke Mobiles",
  },
  {
    id: "rougemont-therapy-centre-sports-massage-and-foot-health-in-b",
    name: "Rougemont Therapy Centre- Sports Massage and Foot Health in Basingstoke",
    type: "physio",
    town: "Basingstoke",
    phone: "07769477033",
    website: "rougemonttherapycentre.co.uk",
    notes: "From Google Maps scrape - 4.8 stars - 36 reviews - Sports injury clinic",
    tier: 2,
    signal: "local",
    batch: "basingstoke-mobiles",
    batchLabel: "Basingstoke Mobiles",
  },
  {
    id: "return-to-movement-ltd",
    name: "Return to Movement Ltd",
    type: "osteo",
    town: "Basingstoke",
    phone: "07807219332",
    website: "returntomovement.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 23 reviews - Osteopath",
    tier: 2,
    signal: "local",
    batch: "basingstoke-mobiles",
    batchLabel: "Basingstoke Mobiles",
  },
  {
    id: "allsports-therapy",
    name: "Allsports Therapy",
    type: "physio",
    town: "Basingstoke",
    phone: "07515174462",
    website: "allsportstherapy.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 112 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "basingstoke-mobiles",
    batchLabel: "Basingstoke Mobiles",
  },
  {
    id: "pippa-blizzard-physiotherapy-in-bentley-farnham",
    name: "Pippa Blizzard - Physiotherapy in Bentley Farnham",
    type: "physio",
    town: "Basingstoke",
    phone: "07714239644",
    website: "pippa-blizzard.co.uk",
    notes: "From Google Maps scrape - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "basingstoke-mobiles",
    batchLabel: "Basingstoke Mobiles",
  },
  {
    id: "fleet-sports-therapy",
    name: "Fleet Sports Therapy",
    type: "physio",
    town: "Basingstoke",
    phone: "07525049144",
    website: "fleetsportstherapy.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 141 reviews - Sports injury clinic",
    tier: 2,
    signal: "local",
    batch: "basingstoke-mobiles",
    batchLabel: "Basingstoke Mobiles",
  },
  {
    id: "michelle-norton-hughes-physiotherapy",
    name: "Michelle Norton-Hughes Physiotherapy",
    type: "physio",
    town: "Basingstoke",
    phone: "07971172116",
    website: "rebuildandthrive.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 35 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "basingstoke-mobiles",
    batchLabel: "Basingstoke Mobiles",
  },
  {
    id: "home-physio",
    name: "Home physio",
    type: "physio",
    town: "Basingstoke",
    phone: "07480867359",
    notes: "From Google Maps scrape - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "basingstoke-mobiles",
    batchLabel: "Basingstoke Mobiles",
  },
  {
    id: "total-recovery",
    name: "Total Recovery",
    type: "physio",
    town: "Basingstoke",
    phone: "07516008051",
    website: "total-recovery.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 13 reviews - Sports injury clinic",
    tier: 2,
    signal: "local",
    batch: "basingstoke-mobiles",
    batchLabel: "Basingstoke Mobiles",
  },
  {
    id: "hook-physiotherapy-sports-injury-clinic",
    name: "Hook Physiotherapy & Sports Injury Clinic",
    type: "physio",
    town: "Basingstoke",
    phone: "07426036787",
    website: "hookphysiotherapy.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 5 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "basingstoke-mobiles",
    batchLabel: "Basingstoke Mobiles",
  },

  // --- READING MOBILES (21 leads) ---
  {
    id: "core-body-clinic",
    name: "Core Body Clinic",
    type: "physio",
    town: "Reading",
    phone: "07748152377",
    website: "corebodyclinic.co.uk",
    notes: "From Google Maps scrape - 4.8 stars - 76 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "reading-mobiles",
    batchLabel: "Reading Mobiles",
  },
  {
    id: "reading-physio",
    name: "Reading Physio",
    type: "physio",
    town: "Reading",
    phone: "07804200419",
    website: "reading-physio.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 46 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "reading-mobiles",
    batchLabel: "Reading Mobiles",
  },
  {
    id: "get-it-right-physio",
    name: "Get it Right Physio",
    type: "physio",
    town: "Reading",
    phone: "07552129230",
    website: "getitrightphysio.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 40 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "reading-mobiles",
    batchLabel: "Reading Mobiles",
  },
  {
    id: "q-care-solutions-ltdgh-physiocare",
    name: "Q Care solutions Ltd(GH Physiocare)",
    type: "physio",
    town: "Reading",
    phone: "07733209673",
    website: "qcaresolution.co.uk",
    notes: "From Google Maps scrape - 4.9 stars - 10 reviews - Physical Therapy Clinic",
    tier: 2,
    signal: "local",
    batch: "reading-mobiles",
    batchLabel: "Reading Mobiles",
  },
  {
    id: "richa-katal-physiotherapy",
    name: "Richa Katal Physiotherapy",
    type: "physio",
    town: "Reading",
    phone: "07423018791",
    website: "richakatalphysiotherapy.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 48 reviews - Physical Therapy Clinic",
    tier: 2,
    signal: "local",
    batch: "reading-mobiles",
    batchLabel: "Reading Mobiles",
  },
  {
    id: "amps-physiotherapy",
    name: "AMPS Physiotherapy",
    type: "physio",
    town: "Reading",
    phone: "07414829437",
    website: "ampsphysio.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 3 reviews - Physical Therapy Clinic",
    tier: 2,
    signal: "local",
    batch: "reading-mobiles",
    batchLabel: "Reading Mobiles",
  },
  {
    id: "elite-performance-physiotherapy",
    name: "Elite Performance Physiotherapy",
    type: "physio",
    town: "Reading",
    phone: "07714847127",
    website: "eliteperformancephysiotherapy.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 2 reviews - Physical Therapy Clinic",
    tier: 2,
    signal: "local",
    batch: "reading-mobiles",
    batchLabel: "Reading Mobiles",
  },
  {
    id: "greener-health-physiotherapy-physiomoves",
    name: "Greener Health Physiotherapy & PHYSIOMOVES",
    type: "physio",
    town: "Reading",
    phone: "07904169054",
    notes: "From Google Maps scrape - 5.0 stars - 23 reviews - Physical Therapy Clinic",
    tier: 2,
    signal: "local",
    batch: "reading-mobiles",
    batchLabel: "Reading Mobiles",
  },
  {
    id: "gemma-miles-soft-tissue-therapy",
    name: "Gemma Miles Soft Tissue Therapy",
    type: "physio",
    town: "Reading",
    phone: "07796696635",
    website: "gemmamilessofttissuetherapy.com",
    notes: "From Google Maps scrape - 5.0 stars - 22 reviews - Women's health clinic",
    tier: 2,
    signal: "local",
    batch: "reading-mobiles",
    batchLabel: "Reading Mobiles",
  },
  {
    id: "physiopracts-physiotherapy-clinic",
    name: "Physiopracts-Physiotherapy Clinic",
    type: "physio",
    town: "Reading",
    phone: "07443177474",
    notes: "From Google Maps scrape - 5.0 stars - 5 reviews - Physical Therapy Clinic",
    tier: 2,
    signal: "local",
    batch: "reading-mobiles",
    batchLabel: "Reading Mobiles",
  },
  {
    id: "remedy-soft-tissue-therapy",
    name: "Remedy Soft Tissue Therapy",
    type: "physio",
    town: "Reading",
    phone: "07920074387",
    website: "myrstt.com",
    notes: "From Google Maps scrape - 5.0 stars - 21 reviews - Sports injury clinic",
    tier: 2,
    signal: "local",
    batch: "reading-mobiles",
    batchLabel: "Reading Mobiles",
  },
  {
    id: "physiopracts-ltd-msk-physio",
    name: "Physiopracts Ltd-MSK Physio",
    type: "physio",
    town: "Reading",
    phone: "07826552521",
    notes: "From Google Maps scrape - 5.0 stars - 4 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "reading-mobiles",
    batchLabel: "Reading Mobiles",
  },
  {
    id: "theosteo-clinic",
    name: "TheOsteo Clinic",
    type: "osteo",
    town: "Reading",
    phone: "07775641732",
    website: "the-osteo.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 29 reviews - Osteopath",
    tier: 2,
    signal: "local",
    batch: "reading-mobiles",
    batchLabel: "Reading Mobiles",
  },
  {
    id: "saunders-sport-performance",
    name: "Saunders Sport Performance",
    type: "physio",
    town: "Reading",
    phone: "07968509527",
    website: "saunderssportperformance.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 10 reviews - Physical Therapy Clinic",
    tier: 2,
    signal: "local",
    batch: "reading-mobiles",
    batchLabel: "Reading Mobiles",
  },
  {
    id: "fixme-ltd",
    name: "FiXme Ltd",
    type: "physio",
    town: "Reading",
    phone: "07878148229",
    notes: "From Google Maps scrape - 4.9 stars - 32 reviews - Physical Therapy Clinic",
    tier: 2,
    signal: "local",
    batch: "reading-mobiles",
    batchLabel: "Reading Mobiles",
  },
  {
    id: "lower-earley-osteopaths",
    name: "Lower Earley Osteopaths",
    type: "osteo",
    town: "Reading",
    phone: "07792580402",
    website: "lowerearleyosteopaths.co.uk",
    notes: "From Google Maps scrape - 4.6 stars - 9 reviews - Osteopath",
    tier: 2,
    signal: "local",
    batch: "reading-mobiles",
    batchLabel: "Reading Mobiles",
  },
  {
    id: "my-wellness",
    name: "My Wellness",
    type: "physio",
    town: "Reading",
    phone: "07597242990",
    website: "mywellness.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 6 reviews - Acupuncturist",
    tier: 2,
    signal: "local",
    batch: "reading-mobiles",
    batchLabel: "Reading Mobiles",
  },
  {
    id: "trinitas-clinic",
    name: "Trinitas Clinic",
    type: "osteo",
    town: "Reading",
    phone: "07545080784",
    website: "trinitasholistichealth.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 8 reviews - Osteopath",
    tier: 2,
    signal: "local",
    batch: "reading-mobiles",
    batchLabel: "Reading Mobiles",
  },
  {
    id: "vitalis-physio",
    name: "Vitalis Physio",
    type: "physio",
    town: "Reading",
    phone: "07432690233",
    website: "vitalisphysio.com",
    notes: "From Google Maps scrape - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "reading-mobiles",
    batchLabel: "Reading Mobiles",
  },
  {
    id: "berkshire-pain-clinic",
    name: "Berkshire Pain Clinic",
    type: "physio",
    town: "Reading",
    phone: "07777106344",
    website: "berkshirepainclinic.co.uk",
    notes: "From Google Maps scrape - 100 Drake Way",
    tier: 2,
    signal: "local",
    batch: "reading-mobiles",
    batchLabel: "Reading Mobiles",
  },
  {
    id: "active-womens-clinic",
    name: "Active Women's Clinic",
    type: "physio",
    town: "Reading",
    phone: "07312121767",
    website: "theactivewomensclinic.com",
    notes: "From Google Maps scrape - 100 Drake Way",
    tier: 2,
    signal: "local",
    batch: "reading-mobiles",
    batchLabel: "Reading Mobiles",
  },

  // --- WINCHESTER MOBILES (10 leads) ---
  {
    id: "the-next-step-physio",
    name: "The Next Step Physio",
    type: "physio",
    town: "Winchester",
    phone: "07708648714",
    website: "thenextstepphysio.com",
    notes: "From Google Maps scrape - 5.0 stars - 38 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "winchester-mobiles",
    batchLabel: "Winchester Mobiles",
  },
  {
    id: "anna-turgoose-physio-wellness",
    name: "Anna Turgoose Physio & Wellness",
    type: "physio",
    town: "Winchester",
    phone: "07803040459",
    website: "annaturgoosephysio.com",
    notes: "From Google Maps scrape - 5.0 stars - 16 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "winchester-mobiles",
    batchLabel: "Winchester Mobiles",
  },
  {
    id: "winchester-wellness",
    name: "Winchester Wellness",
    type: "physio",
    town: "Winchester",
    phone: "07539119627",
    website: "winchesterwellness.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 41 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "winchester-mobiles",
    batchLabel: "Winchester Mobiles",
  },
  {
    id: "lovetomove-physiotherapy",
    name: "Lovetomove Physiotherapy",
    type: "physio",
    town: "Winchester",
    phone: "07941254959",
    website: "lovetomovephysiotherapy.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 19 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "winchester-mobiles",
    batchLabel: "Winchester Mobiles",
  },
  {
    id: "simply-thrive-physio-and-pilates",
    name: "Simply Thrive Physio and Pilates",
    type: "physio",
    town: "Winchester",
    phone: "07846128479",
    website: "simplythrive.uk",
    notes: "From Google Maps scrape - 5.0 stars - 19 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "winchester-mobiles",
    batchLabel: "Winchester Mobiles",
  },
  {
    id: "run-physio",
    name: "Run Physio",
    type: "physio",
    town: "Winchester",
    phone: "07944022438",
    website: "run-physio.co.uk",
    notes: "From Google Maps scrape - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "winchester-mobiles",
    batchLabel: "Winchester Mobiles",
  },
  {
    id: "inner-strength-physiotherapy",
    name: "Inner Strength Physiotherapy",
    type: "physio",
    town: "Winchester",
    phone: "07462353316",
    website: "innerstrengthphysiotherapy.com",
    notes: "From Google Maps scrape - Physical Therapy Clinic",
    tier: 2,
    signal: "local",
    batch: "winchester-mobiles",
    batchLabel: "Winchester Mobiles",
  },
  {
    id: "newton-physiotherapy-winchester",
    name: "Newton Physiotherapy - Winchester",
    type: "physio",
    town: "Winchester",
    phone: "07988266411",
    website: "newtonphysiotherapy.co.uk",
    notes: "From Google Maps scrape - Physical Therapy Clinic",
    tier: 2,
    signal: "local",
    batch: "winchester-mobiles",
    batchLabel: "Winchester Mobiles",
  },
  {
    id: "emma-ghazaros-physiotherapy",
    name: "Emma Ghazaros Physiotherapy",
    type: "physio",
    town: "Winchester",
    phone: "07719196527",
    website: "emmaghazarosphysiotherapy.co.uk",
    notes: "From Google Maps scrape - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "winchester-mobiles",
    batchLabel: "Winchester Mobiles",
  },
  {
    id: "elle-tisch-physiotherapy",
    name: "Elle Tisch Physiotherapy",
    type: "physio",
    town: "Winchester",
    phone: "07717888157",
    website: "physiotherapywinchester.com",
    notes: "From Google Maps scrape - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "winchester-mobiles",
    batchLabel: "Winchester Mobiles",
  },

  // --- CAMBERLEY MOBILES (10 leads) ---
  {
    id: "quinntessential-sports-therapy",
    name: "Quinntessential Sports Therapy",
    type: "physio",
    town: "Camberley",
    phone: "07810100175",
    website: "mqst.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 8 reviews - Sports injury clinic",
    tier: 2,
    signal: "local",
    batch: "camberley-mobiles",
    batchLabel: "Camberley Mobiles",
  },
  {
    id: "gemini-osteopathy",
    name: "Gemini Osteopathy",
    type: "osteo",
    town: "Camberley",
    phone: "07747740504",
    website: "geminiosteopathy.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 298 reviews - Sports massage therapist",
    tier: 2,
    signal: "local",
    batch: "camberley-mobiles",
    batchLabel: "Camberley Mobiles",
  },
  {
    id: "camberley-sports-remedial-soft-tissue-therapy",
    name: "Camberley Sports & Remedial Soft Tissue Therapy",
    type: "physio",
    town: "Camberley",
    phone: "07548223539",
    notes: "From Google Maps scrape - Sports injury clinic",
    tier: 2,
    signal: "local",
    batch: "camberley-mobiles",
    batchLabel: "Camberley Mobiles",
  },
  {
    id: "goodwood-spinal-health",
    name: "Goodwood Spinal Health",
    type: "chiro",
    town: "Camberley",
    phone: "07917880251",
    website: "gwspinalhealth.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 145 reviews - Chiropractor",
    tier: 2,
    signal: "local",
    batch: "camberley-mobiles",
    batchLabel: "Camberley Mobiles",
  },
  {
    id: "fleet-physiotherapy-and-wellness",
    name: "Fleet Physiotherapy and Wellness",
    type: "physio",
    town: "Camberley",
    phone: "07971131585",
    website: "fleetphysio.com",
    notes: "From Google Maps scrape - 5.0 stars - 72 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "camberley-mobiles",
    batchLabel: "Camberley Mobiles",
  },
  {
    id: "george-gore-sports-therapy",
    name: "George Gore Sports Therapy",
    type: "physio",
    town: "Camberley",
    phone: "07492437032",
    website: "georgegoresportstherapy.com",
    notes: "From Google Maps scrape - 5.0 stars - 49 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "camberley-mobiles",
    batchLabel: "Camberley Mobiles",
  },
  {
    id: "pure-health-clinic-osteopathy-sports-massage-dry-needling-an",
    name: "Pure Health Clinic - Osteopathy, Sports Massage, Dry Needling and Exercise Rehab",
    type: "osteo",
    town: "Camberley",
    phone: "07786921817",
    website: "clinicpurehealth.com",
    notes: "From Google Maps scrape - 5.0 stars - 33 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "camberley-mobiles",
    batchLabel: "Camberley Mobiles",
  },
  {
    id: "reform-renew-osteopathy",
    name: "Reform & Renew Osteopathy",
    type: "osteo",
    town: "Camberley",
    phone: "07544516816",
    website: "randrosteopathy.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 28 reviews - Sports injury clinic",
    tier: 2,
    signal: "local",
    batch: "camberley-mobiles",
    batchLabel: "Camberley Mobiles",
  },
  {
    id: "valkyrie-physiotherapy",
    name: "Valkyrie Physiotherapy",
    type: "physio",
    town: "Camberley",
    phone: "07428114965",
    website: "valkyriehq.co.uk",
    notes: "From Google Maps scrape - 5.0 stars - 26 reviews - Physiotherapist",
    tier: 2,
    signal: "local",
    batch: "camberley-mobiles",
    batchLabel: "Camberley Mobiles",
  },
  {
    id: "ew-sports-therapy-sports-massage-injury-clinic",
    name: "EW Sports Therapy - Sports Massage & Injury Clinic",
    type: "physio",
    town: "Camberley",
    phone: "07983505809",
    website: "ewsportstherapy.com",
    notes: "From Google Maps scrape - 5.0 stars - 108 reviews - Sports injury clinic",
    tier: 2,
    signal: "local",
    batch: "camberley-mobiles",
    batchLabel: "Camberley Mobiles",
  },
];

// --- Batch helper ---
export function getBatches(): { id: string; label: string; count: number }[] {
  const batchMap = new Map<string, { label: string; count: number }>();
  for (const lead of LEADS) {
    const existing = batchMap.get(lead.batch);
    if (existing) {
      existing.count++;
    } else {
      batchMap.set(lead.batch, { label: lead.batchLabel, count: 1 });
    }
  }
  return Array.from(batchMap.entries()).map(([id, data]) => ({ id, ...data }));
}
